### ISSUE TITLE
Convert Paper Wireframe into Digital Wireframe

### ISSUE THREAD

**Issue by contactvaibhavi** [upaytech/as-client#5]
**I'm submitting a ...**

- [] bug report
- [x] feature request

**Describe the bug/feature:**
We have received Paper Wireframes from the UPAY Person-of-contact. However, for development process, digital wireframes would be more suitable.

**Current [behaviour:**]
![img-20190305-wa0016](https://user-images.githubusercontent.com/32491912/54003608-c2b47c80-4178-11e9-843a-ac89a6540ce8.jpg)
![img-20190305-wa0015](https://user-images.githubusercontent.com/32491912/54003609-c2b47c80-4178-11e9-990f-88625d23aebd.jpg)
![img-20190305-wa0014](https://user-images.githubusercontent.com/32491912/54003610-c34d1300-4178-11e9-8c6f-acaad81d63c6.jpg)

Paper Wireframe for Three pages

**Expected behavior:**
Digital Wireframe for all three pages

**Want to work on issue?**

- [] Yes
- [] No

**Comment by vaibhav-sharma-frontend** [comment]
@Vaibhavi24 can I work on this issue. I'm a gssoc participant.

**Comment by contactvaibhavi** [comment]
> @Vaibhavi24 can I work on this issue. I'm a gssoc participant.

Actually, an UPAY member is working on it, we'll assign it to him!

**Comment by shpiyu** [comment]
completed
