### ISSUE TITLE
Create home component

### ISSUE THREAD

**Issue by shpiyu** [upaytech/as-client#7]
Refer the attached wireframe and create a home component for the website along with necessary sub-components. 
[Upay_Apnasaman_Wireframe.pdf](https://github.com/upaytech/as-client/files/2996318/Upay_Apnasaman_Wireframe.pdf)

**Comment by SarthakSri98** [comment]
Hello, @shpiyu ,I would like to work on this issue please.

**Comment by shpiyu** [comment]
Sure, please start and feel free to reach out to me on our slack group  if you've any doubt.

**Comment by vaibhav-sharma-frontend** [comment]
@SarthakSri98 are you still working on this issue?

**Comment by shpiyu** [comment]
@vsharma20v closing this issue. Will provide more information on this project later.
